### PR TITLE
Pull request for delegate

### PR DESCRIPTION
**Pull request by adapole**
1. Removed the isDev
2. Changed signer

### CODE REVIEW

**Comment by Adg0** [comment]
I agree `giveRightToVoteOld.ts` is not needed anymore. You could delete the file

**Review by Muu79 — CHANGES_REQUESTED** [review]
wait was fallback providor not working for you? if so lemme know, also could you try editing the original file so it's easier to see what you fixed exactly.

**Comment by Adg0** [comment]
Fallback provider works for me, I don't know why it was removed in new `givRightToVote.ts`

**Comment by adapole** [comment]
I made the scripting similar to the others. 
And the changes are at [Line 25](https://github.com/Muu79/Encode-Club-Solidity-Team-12/blob/dev/week-2/scripts/delegateVote.ts#L25) to Line 40 in the dev branch. 

Mainly the if statement at [Line 22, of main branch](https://github.com/Muu79/Encode-Club-Solidity-Team-12/blob/main/week-2/scripts/delegateVote.ts#L22) it's not necessary since hardhat runtime environment isn't being used for goerli testnet.

And missing await at [Line 49, of main branch](https://github.com/Muu79/Encode-Club-Solidity-Team-12/blob/main/week-2/scripts/delegateVote.ts#L49)

Also fallbackprovider work for me. It's being used in the [`delegateVote.ts`](https://github.com/Muu79/Encode-Club-Solidity-Team-12/blob/dev/week-2/scripts/delegateVote.ts#L25)

**Comment by Muu79** [comment]
Oh okay, i think you might have been a commit behind since i belive i fixed those issues [here](https://github.com/Muu79/Encode-Club-Solidity-Team-12/pull/15/commits/452c2bfd600f374a14e9fdabe8d7e773c87fe024). Thanks for making it match the standard though.

**Pull request merged**
